# Generated by Django 5.1.5 on 2025-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='test@testmail.com', max_length=254),
        ),
    ]
