# Generated by Django 5.1.6 on 2025-03-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_phone_order_shipping_address_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
