# Generated by Django 5.1.6 on 2025-02-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_sale_product_is_show_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Image'},
        ),
    ]
