# Generated by Django 5.1.6 on 2025-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_color_size_alter_product_is_show_productattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='prices',
        ),
    ]
