# Generated by Django 5.1.7 on 2025-03-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='show/hide product'),
        ),
    ]
