# Generated by Django 5.1.6 on 2025-04-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productattributes_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
